services:
  web:
    build: .
    image: mywebapp:latest
    ports:
      - "127.0.0.1:15000:5000"
    depends_on:
      - db
    networks:
      - frontend
    read_only: true
    security_opt:
      - "no-new-privileges:true"
    environment:
      - APP_PASSWORD=${APP_PASSWORD}
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    
networks:
  frontend:
  backend:
volumes:
  postgres_data: